import * as appsync from '@aws-cdk/aws-appsync-alpha';
import { aws_dynamodb as dynamodb, Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';



export class PresentationStack extends Stack {

    constructor(scope: Construct, id: string, dbTable: dynamodb.Table, props?: StackProps) {
        super(scope, id, props);

        //appSync

        const api = new appsync.GraphqlApi(this, 'NewsApi', {
            name: 'NewsApi',
            schema: appsync.Schema.fromAsset('./src/whatsNew.graphql'),
            authorizationConfig: {
                defaultAuthorization: {
                    authorizationType: appsync.AuthorizationType.IAM,
                },
            }
        });


        const dataSource = api.addDynamoDbDataSource("NewsDataSource", dbTable)
        //todo: adjust the request Mapping Template
        dataSource.createResolver({
            typeName: 'Query',
            fieldName: 'getAWSNews',
            requestMappingTemplate: appsync.MappingTemplate.dynamoDbScanTable(),
            //autogenerated response using $ctx.result is not working 
            // responseMappingTemplate: appsync.MappingTemplate.dynamoDbResultList(),
            responseMappingTemplate: appsync.MappingTemplate.fromString("$util.toJson($context.result)")
        });
        dataSource.createResolver({
            typeName: 'Query',
            fieldName: 'listAWSNews',
            requestMappingTemplate: appsync.MappingTemplate.fromString(`{
        "version": "2017-02-28",
        "operation": "Scan",
        "filter": #if($context.args.filter) $util.transform.toDynamoDBFilterExpression($ctx.args.filter) #else null #end,
        "limit": $util.defaultIfNull($ctx.args.limit, 20),
        "nextToken": $util.toJson($util.defaultIfNullOrEmpty($ctx.args.nextToken, null)),
      }`),
            //autogenerated response using $ctx is not working 
            // responseMappingTemplate: appsync.MappingTemplate.dynamoDbResultList(),
            responseMappingTemplate: appsync.MappingTemplate.fromString("$util.toJson($context.result)")
        });


    }



}